### ISSUE TITLE
项目缺失DaggerActivityComponent类

### ISSUE THREAD

**Issue by xiaosong520** [a371166028/likequanmintv#11]
如题，import android.marshon.likequanmintv.di.component.DaggerActivityComponent; 这个类在项目中缺失了 @a371166028

**Comment by chenchengyin** [comment]
你的编译仓库不对


发自网易邮箱大师
在2017年03月22日 11:02，xiaosongzeem 写道:

如题，import android.marshon.likequanmintv.di.component.DaggerActivityComponent; 这个类在项目中缺失了 @a371166028

**Comment by xiaosong520** [comment]
@a371166028 Make Project之后 没问题了，3Q
